language: ruby
rvm:
  2.3.1

env:
  - REPOSITORY=hpi-swa/RSqueak VM=rsqueak USE_SHA=1
  - REPOSITORY=OpenSmalltalk/opensmalltalk-vm VM=cog
  - REPOSITORY=OpenSmalltalk/opensmalltalk-vm VM=stack
  - REPOSITORY=OpenSmalltalk/opensmalltalk-vm VM=sista
  # - REPOSITORY=OpenSmalltalk/opensmalltalk-vm VM=coldsista
  # - REPOSITORY=OpenSmalltalk/opensmalltalk-vm VM=counters
  # - REPOSITORY=OpenSmalltalk/opensmalltalk-vm VM=nocounters

script:
  - bundle exec ruby .travis.rb
