language: python
python:
  - 2.7
env:
  matrix:
    - TEST_TYPE=default
    - BUILD_ARCH=32bit
    - BUILD_ARCH=64bit
    - BUILD_TYPE=test
    - BUILD_TYPE=build
matrix:
  fast_finish: true
  allow_failures:
    - env: BUILD_ARCH=64bit
install:
  - export chroot="$PWD"/buildroot.i386
  - .travis/setup_chroot.sh
script:
  - if [ "$BUILD_TYPE" == test ]; then .travis/test.sh; fi
  - if [ "$BUILD_TYPE" == build ]; then .travis/build.sh; fi
