language: python
python: pypy
sudo: required
dist: trusty
group: edge
notifications:
  irc:
    channels:
      - chat.freenode.net/#rsqueak
    use_notice: true
    skip_join: true
  slack: mp2016h:7AUemvDdkxof6Shbu514mDyX
branches:
  except:
    - /^v[0-9]/  # Ignore version tags
    - windows-build
jobs:
  include:
    - stage: "Main builds"
      env: BUILD_ARCH=32bit TEST_TYPE=default
    - env: BUILD_ARCH=32bit
    - env: BUILD_ARCH=32bit TEST_TYPE=coverage
    # - env: BUILD_ARCH=lldebug
    - env: BUILD_ARCH=64bit TEST_TYPE=default
    - env: BUILD_ARCH=64bit

    - stage: "Mac builds"
      os: osx
      osx_image: xcode7.3
      language: cpp
      env: BUILD_ARCH=64bit TEST_TYPE=default
    - os: osx
      osx_image: xcode7.3
      language: cpp
      env: BUILD_ARCH=64bit

    - stage: "Plugin builds"
      env: BUILD_ARCH=64bit PLUGINS=RubyPlugin
    - os: osx
      osx_image: xcode7.3
      language: cpp
      env: BUILD_ARCH=64bit PLUGINS=RubyPlugin
    # - env: BUILD_ARCH=64bit PLUGINS=DatabasePlugin

    - stage: "ARM builds"
      env: SB2="$PWD/raspbian_arm" SB2NAME="rasp" BUILD_ARCH=armv6
    - env: SB2="$PWD/raspbian_arm" SB2NAME="rasp" BUILD_ARCH=armv7-a
    - env: SB2="$PWD/raspbian_arm" SB2NAME="rasp" BUILD_ARCH=armv8-a
  allow_failures:
    # - env: BUILD_ARCH=64bit PLUGINS=DatabasePlugin
    - env: BUILD_ARCH=64bit PLUGINS=RubyPlugin
  fast_finish: true
install: .travis/install_requirements.sh
script: .travis/build.sh
after_success: .travis/success.sh
