language: python
python:
  - 2.7
branches:
  except:
    - windows-build
env:
  global:
    - OSXREPO=timfel/RSqueak-MacOSXBuild
    - TEST_TYPE=default 
  matrix:
    - BUILD_ARCH=32bit BUILD_TYPE=test
    - BUILD_ARCH=32bit BUILD_TYPE=build
    - BUILD_ARCH=arm BUILD_TYPE=build
install:
  - .travis/trigger-osx-build.sh || echo 0
  - .travis/install_requirements.sh
script:
  - if [ "$BUILD_TYPE" == test ]; then .travis/test.sh; fi
  - if [ "$BUILD_TYPE" == build ]; then .travis/build-linux.sh; fi
