language: python
python:
  - 2.7
env:
  global:
    - TEST_TYPE=default 
    - EXECUTE_JITTESTS=yes
  matrix:
    - BUILD_ARCH=32bit BUILD_TYPE=test
    - BUILD_ARCH=32bit BUILD_TYPE=build
    - BUILD_ARCH=64bit BUILD_TYPE=test
    - BUILD_ARCH=64bit BUILD_TYPE=build
matrix:
  fast_finish: true
  allow_failures:
    - env: BUILD_ARCH=64bit BUILD_TYPE=test
    - env: BUILD_ARCH=64bit BUILD_TYPE=build
install:
  - .travis/install_requirements.sh
  - export chroot="$PWD"/buildroot.i386
  - if [ "$BUILD_ARCH" == 32bit ]; then .travis/setup_chroot.sh; fi
script:
  - if [ "$BUILD_TYPE" == test ]; then .travis/test.sh; fi
  - if [ "$BUILD_TYPE" == build ]; then .travis/build.sh; fi
after_success:
  - git config --global user.email "travis-ci@travis.org"
  - git config --global user.name "Travis CI"
  - git clone "https://${GH_TOKEN}@github.com/HPI-SWA-Lab/RSqueak-MacOSXBuild.git"
  - cd RSqueak-MacOSXBuild
  - git commit --allow-empty -m "Triggered by ${$TRAVIS_COMMIT}"
  - git push origin master:$TRAVIS_BRANCH
