language: smalltalk
sudo: required
os: osx
smalltalk:
- Squeak-latest
after_success: ./prepare.sh
before_install:
- openssl aes-256-cbc -K $encrypted_fa398914a9db_key -iv $encrypted_fa398914a9db_iv
  -in certs/dist.zip.enc -out certs/dist.zip -d
