language: python
python:
  - 2.7
env:
  global:
    - secure: "f3+bJthcOf3YPc2w+s0d3dEMGvIfeutu6zAjpTT8Nb/Q/YjieUVHxdtaf+TgcauHgfzzOZ+26klXz0G9cKiKjwMxv/916fZofLn/Bh4kOUnHXYHYyTqkmLyUWlYMktdVu3/pMjY1waYQjNtqlo6q4opsiqBA5rLJ5CAF6NkZBLg="
    - OSXREPO=timfel/RSqueak-MacOSXBuild
    - TEST_TYPE=default 
    - EXECUTE_JITTESTS=yes
  matrix:
    - BUILD_ARCH=32bit BUILD_TYPE=test
    - BUILD_ARCH=32bit BUILD_TYPE=build
    - BUILD_ARCH=64bit BUILD_TYPE=test
    - BUILD_ARCH=64bit BUILD_TYPE=build
matrix:
  fast_finish: true
  allow_failures:
    - env: BUILD_ARCH=64bit BUILD_TYPE=test
    - env: BUILD_ARCH=64bit BUILD_TYPE=build
install:
  - .travis/trigger-osx-build.sh || 0
  - .travis/install_requirements.sh
  - export chroot="$PWD"/buildroot.i386
  - if [ "$BUILD_ARCH" == 32bit ]; then .travis/setup_chroot.sh; fi
script:
  - if [ "$BUILD_TYPE" == test ]; then .travis/test.sh; fi
  - if [ "$BUILD_TYPE" == build ]; then .travis/build.sh; fi
cache:
  directories:
    - $PWD/buildroot.i386
