language: python
python:
  - 2.7
branches:
  except:
    - windows-build
env:
  global:
    - OSXREPO=timfel/RSqueak-MacOSXBuild
    - TEST_TYPE=default 
    - LIBRARY_PATH=$LIBRARY_PATH:$HOME/SDL2/lib
    - C_INCLUDE_PATH=$C_INCLUDE_PATH:$HOME/SDL2/include
  matrix:
    - BUILD_ARCH=32bit BUILD_TYPE=test
    - BUILD_ARCH=32bit BUILD_TYPE=build
    - BUILD_ARCH=lldebug BUILD_TYPE=build
    - BUILD_ARCH=armv6 BUILD_TYPE=build SB2="$PWD/raspbian_arm" SB2NAME="rasp"
    - BUILD_ARCH=armv7 BUILD_TYPE=build
install:
  - .travis/trigger-osx-build.sh || echo 0
  - .travis/install_requirements.sh
script:
  - if [ "$BUILD_TYPE" == test ]; then .travis/test.sh; fi
  - if [ "$BUILD_TYPE" == build ]; then .travis/build-linux.sh; fi
