language: ruby
rvm:
  2.3.1

matrix:
  - env: REPOSITORY=HPI-SWA-Lab/RSqueak VM=rsqueak USE_SHA=1
  - env: REPOSITORY=OpenSmalltalk/opensmalltalk-vm VM=cog

script:
  - bundle install
  - bundle exec ruby .travis.rb
