language: python
python:
  - 2.7
env:
  secure: "HrufNrK8W5R6/zabDitBG4KgsSSIPVoo2/eS7++JDeoen6fKHrbcMEXcvX1SU3P1sfxkW8nezwKecK37WVehJMx6wooVJVY4pkCqsOcd1NFGoTHZIFDNlcspz67IBDAGVTP7yLCNdigi+ocu6ZaS1EYO+N+gnKnWONsFQLriOMA="
  global:
    - TEST_TYPE=default 
    - EXECUTE_JITTESTS=yes
  matrix:
    - BUILD_ARCH=32bit BUILD_TYPE=test
    - BUILD_ARCH=32bit BUILD_TYPE=build
    - BUILD_ARCH=64bit BUILD_TYPE=test
    - BUILD_ARCH=64bit BUILD_TYPE=build
matrix:
  fast_finish: true
  allow_failures:
    - env: BUILD_ARCH=64bit BUILD_TYPE=test
    - env: BUILD_ARCH=64bit BUILD_TYPE=build
install:
  - if [ "$BUILD_TYPE" == build ]; then gem install travis; fi
  - if [ "$BUILD_TYPE" == build ]; then travis restart --no-interactive -t $TRAVIS_TOKEN -r timfel/RSqueak-MacOSXBuild; fi
  - false
  - .travis/install_requirements.sh
  - export chroot="$PWD"/buildroot.i386
  - if [ "$BUILD_ARCH" == 32bit ]; then .travis/setup_chroot.sh; fi
script:
  - if [ "$BUILD_TYPE" == test ]; then .travis/test.sh; fi
  - if [ "$BUILD_TYPE" == build ]; then .travis/build.sh; fi
