language: python
python:
  - 2.7
env:
  matrix:
    - TEST_TYPE=default
    - TEST_TYPE=quick
    - TEST_TYPE=slow
    - TEST_TYPE=translate
install:
  - export chroot="$PWD"/buildroot.i386
  - .travis/setup_chroot.sh
script:
  - "case \"$TEST_TYPE\" in
       default|quick|slow)
         case \"TEST_TYPE\" in
           default) testflag= ;;
           quick) testflag=-Q ;;
           slow) testflag=-S ;;
         sudo i386 chroot \"$chroot\" sh -c \"cd $PWD && echo $(pwd) && ls && PYTHONPATH=$PYTHONPATH:pypy-pypy/:pypy-rsdl/:. python2.7 pypy-pypy/pytest.py -s $testflag spyvm/test/\"
         ;;
       
       translate)
         sudo i386 chroot \"$chroot\" sh -c \"cd $PWD && echo $(pwd) && ls && PYTHONPATH=$PYTHONPATH:pypy-pypy/:pypy-rsdl/:. python2.7 pypy-pypy/rpython/bin/rpython --batch -Ojit targetimageloadingsmalltalk.py\"
         ;;
     esac"
