language: cpp
sudo: required
dist: trusty
group: edge
os:
  - linux
  - osx
osx_image: xcode7.3
notifications:
  irc:
    channels:
      - chat.freenode.net/#rsqueak
    use_notice: true
    skip_join: true
  slack: mp2016h:7AUemvDdkxof6Shbu514mDyX
branches:
  except:
    - /^v[0-9]/  # Ignore version tags
    - windows-build
env:
  global:
    - SB2="$PWD/raspbian_arm"
    - SB2NAME="rasp"
    - PATH=$PATH:$HOME/SDL2/bin
    - LIBRARY_PATH=$LIBRARY_PATH:$HOME/SDL2/lib
    - C_INCLUDE_PATH=$C_INCLUDE_PATH:$HOME/SDL2/include
  matrix:
    - BUILD_ARCH=32bit TEST_TYPE=default
    - BUILD_ARCH=32bit
    - BUILD_ARCH=32bit TEST_TYPE=coverage
    # - BUILD_ARCH=lldebug
    - BUILD_ARCH=64bit TEST_TYPE=default
    - BUILD_ARCH=64bit
    - BUILD_ARCH=armv6
    - BUILD_ARCH=armv7-a
    - BUILD_ARCH=armv8-a
matrix:
  exclude:
    - os: osx
      env: BUILD_ARCH=32bit TEST_TYPE=coverage
    - os: osx
      env: BUILD_ARCH=armv6
    - os: osx
      env: BUILD_ARCH=armv7-a
    - os: osx
      env: BUILD_ARCH=armv8-a
  allow_failures:
    - env: BUILD_ARCH=64bit
    - env: BUILD_ARCH=64bit TEST_TYPE=default
    # - env: BUILD_ARCH=armv6
    # - env: BUILD_ARCH=armv7-a
    # - env: BUILD_ARCH=armv8-a
  fast_finish: true
install: .travis/install_requirements.sh
script: .travis/build.sh
after_success: .travis/success.sh
