skip_tags: true
branches:
  only:
    - master
    - windows-build

environment:
  DeployCredentials:
    secure: jRxEUfeTDZh8Ju6y08aXrnCz6vemvPOwBef3qBC4ep0=
  VisualStudioVersion: 9.0
  SDL_VIDEODRIVER: dummy

  matrix:
    - buildscript: unittests.py
    - buildscript: build.py
    - buildscript: build.py
      buildargs: -- --plugins=ruby_plugin

matrix:
  fast_finish: true

shallow_clone: true
platform: x86
install:
  - cmd: C:\\Python27\\python .build/download_dependencies.py ruby_plugin
build: false
test_script:
  - cmd: .appveyor/rsqueak-build.bat

cache:
  - .build/pypy -> .appveyor/cache_tag
  - .build/rsdl -> .appveyor/cache_tag
  - .build/SDL -> .appveyor/binary_cache_tag
  - .build/rply -> .appveyor/binary_cache_tag
  - .build/appdirs -> .appveyor/binary_cache_tag
  - .build/topaz -> .appveyor/binary_cache_tag
