skip_tags: true
shallow_clone: true
platform: x86
configuration: Build
before_build:
  - ps: "cp .appveyor/* ."
build:
  project: rsqueak.msbuild
on_success:
  - cmd: "%WINDIR%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -NonInteractive -executionpolicy Unrestricted -command \"& { .\\rsqueak-upload.ps1 }\""
