skip_tags: true
branches:
  only:
    - master
    - windows-build

environment:
  VisualStudioVersion: 9.0

shallow_clone: true
platform: x86
install:
  - cmd: C:\\Python27\\python .build/download_dependencies.py
build: false
test_script:
  - cmd: .appveyor/rsqueak-build.bat
on_success:
  - cmd: "%WINDIR%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -NonInteractive -executionpolicy Unrestricted -command \"& { .\\.appveyor\\rsqueak-upload.ps1 }\""

cache:
  - .build/pypy -> .appveyor/cache_tag
  - .build/rsdl -> .appveyor/cache_tag
  - .build/pypy-win32 -> .appveyor/cache_tag
  - .build/SDL -> .appveyor/cache_tag
